name: Teste

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagem Docker
        run: |
          docker build -t wallacelentes/devops:tagname .
          docker push wallacelentes/devops:tagname

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Instalar dependências
        run: pip install Flask
      - name: Executar análise de segurança
        uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Puxar imagem Docker
        run: docker pull wallacelentes/devops:tagname

      - name: Executar imagem Docker
        run: docker run wallacelentes/devops:tagname
